console.log('🗃️  Trackify Database Management Scripts');
console.log('=====================================');
console.log('');
console.log('📋 Available Commands:');
console.log('');
console.log('🔧 Setup & Testing:');
console.log('  npm run test:db           - Test database connection');
console.log('');
console.log('📊 Data Management:');
console.log('  npm run init:data         - Initialize with sample data');
console.log('  npm run migrate:collections - Migrate to singular collection names');
console.log('');
console.log('🌐 Development:');
console.log('  npm run dev               - Start development server');
console.log('  npm run build             - Build for production');
console.log('');
console.log('🔗 Test URLs (after npm run dev):');
console.log('  http://localhost:3000/api/test/db  - Database connection test');
console.log('  http://localhost:3000/api/tools    - Tools API');
console.log('  http://localhost:3000/api/users    - Users API');
console.log('  http://localhost:3000/api/payments - Payments API');
console.log('  http://localhost:3000/api/donations - Donations API');
console.log('  http://localhost:3000/api/purchases - Purchases API');
console.log('');
console.log('📊 Current Collections (singular names):');
console.log('  💰 payment    - Payment records');
console.log('  🎁 donation   - Donation records');
console.log('  🛒 purchase   - Purchase records');
console.log('  🔧 tools      - Tools inventory');
console.log('  👥 user       - User accounts');
console.log('');
console.log('📝 Quick Start:');
console.log('  1. npm run test:db        - Verify MongoDB connection');
console.log('  2. npm run init:data      - Add sample data');
console.log('  3. npm run dev            - Start server');
console.log('  4. Open: http://localhost:3000/api/tools');
console.log('');
console.log('💡 Tip: Run this script anytime with "npm run db:help"');
console.log('');